Repository hmcts/pip-publication-services, pull requests merged in 2023-04, with the labels that each got.

#290 PUB-1693 Move shared model classes to pip-data-models
  build.gradle
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/authentication/roles/IsAdmin.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/helpers/CaseNameHelper.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Artefact.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/ArtefactType.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/FileType.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Language.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/ListType.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Location.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Sensitivity.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/LocationSubscriptionDeletion.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/ThirdPartySubscription.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/ThirdPartySubscriptionArtefact.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/helpers/CaseNameHelperTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-290

#300 PUB-1970 - Updated dependencies
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-300

#292 PUB-1056 - Rejection reasons
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/MediaRejectionEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationService.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-292

#302 PUB-1991 - Updated gradle
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-302

#305 Update spring boot version to fix CVE-2023-20863
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-305
