Repository hmcts/pip-publication-services, pull requests merged in 2023-07, with the labels that each got.

#336 Suppress CVE-2023-34462
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-336

#325 PUB-1687 - Upgrade to spring boot 3
  bin/init.sh
  build.gradle
  config/owasp/suppressions.xml
  config/pmd/ruleset.xml
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/SpringSecurityConfig.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/RootController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/exceptions/ThirdPartyServiceException.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/DuplicatedMediaEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/InactiveUserNotificationEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/SubscriptionEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/validation/SubscriptionsConstraint.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/validation/SubscriptionsConstraintValidator.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/configuration/SpringSecurityConfigTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java
  src/test/resources/application-test.yaml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-325

#337 PUB-2079 Update dependencies + gradle
  build.gradle
  charts/pip-publication-services/Chart.yaml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/GlobalExceptionHandlerTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-337

#342 Updated nightly build
  Jenkinsfile_nightly
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-342

#344 Fixed vulnerability
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-344
