Repository hmcts/pip-publication-services, pull requests merged in 2023-12, with the labels that each got.

#389 PUB-2234 Rate limiting on email sending
  README.md
  build.gradle
  charts/pip-publication-services/Chart.yaml
  charts/pip-publication-services/values.yaml
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyRateLimitTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/utils/RedisConfigurationFunctionalTestBase.java
  src/integrationTest/resources/application-functional-rate-limit.yaml
  src/integrationTest/resources/application-functional.yaml
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/RateLimitConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/RedisConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/exceptions/TooManyEmailsException.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/EmailLimit.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/RateLimitingService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/client/EmailClientTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/exceptions/CustomExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/notify/TemplatesTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/RateLimitingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/utils/RedisConfigurationTestBase.java
  src/test/resources/application-test.yaml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-389

#394 PUB-2265 - Dependency Updates
  build.gradle
  charts/pip-publication-services/Chart.yaml
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-394

#393 PUB-2193 Add APIM infrastructure for OTP endpoint
  infrastructure/data.tf
  infrastructure/main.tf
  infrastructure/resources/api-policy/api-policy.xml
  infrastructure/resources/operation-policies/sendOtpEmail.xml
  infrastructure/resources/operation-policies/welcome.xml
  infrastructure/resources/swagger/api-swagger.json
  infrastructure/tf-apim-api.tf
  infrastructure/tf-apim-logger.tf
  infrastructure/tf-apim-operations.tf
  infrastructure/variables.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-publication-services-pr-393

#384 PUB-2193 Add new endpoint for OTP email
  README.md
  publication-services-arch.png
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/B2cNotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/OtpEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationService.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/B2cNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-384

#395 PUB-2193 Fixed key vault location
  infrastructure/resources/api-policy/api-policy.xml
  infrastructure/resources/operation-policies/sendOtpEmail.xml
  infrastructure/resources/operation-policies/welcome.xml
  infrastructure/tf-apim-api.tf
  infrastructure/tf-apim-operations.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-publication-services-pr-395

#396 Updated owasp version
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-396

#390 PUB-1988 - Updated data models versions in OPA press list
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-390
