Repository hmcts/pip-publication-services, pull requests merged in 2023-06, with the labels that each got.

#316 PUB-1960 Fix subscription email not sent if PDF file over 2MB
  build.gradle
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-316

#324 PUB-1900 update Gradle to V8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-324

#326 Suppress CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-326
