Repository hmcts/pip-publication-services, pull requests merged in 2023-11, with the labels that each got.

#380 PUB-2153 Add OPA Press List listType
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-380

#383 PUB-2206 - Dependency Updates
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/state.tf
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-383

#386 Set up perftest env
  config/owasp/suppressions.xml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/providers.tf
  infrastructure/state.tf
  infrastructure/stg.tfvars
  infrastructure/test.tfvars
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-386

#385 PUB-2193 Add publication services APIM for OTP
  infrastructure/data.tf
  infrastructure/main.tf
  infrastructure/resources/api-policy/api-policy.xml
  infrastructure/resources/operation-policies/sendOtpEmail.xml
  infrastructure/resources/operation-policies/welcome.xml
  infrastructure/resources/swagger/api-swagger.json
  infrastructure/tf-apim-api.tf
  infrastructure/tf-apim-operations.tf
  infrastructure/variables.tf
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-385

#387 PUB-2193 Update APIM infrastructure
  infrastructure/main.tf
  infrastructure/resources/api-policy/api-policy.xml
  infrastructure/resources/operation-policies/sendOtpEmail.xml
  infrastructure/resources/operation-policies/welcome.xml
  infrastructure/resources/swagger/api-swagger.json
  infrastructure/tf-apim-operations.tf
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-387
