Repository hmcts/pip-publication-services, pull requests merged in 2024-08, with the labels that each got.

#451 PUB-2545 - Lower file generation limit
  src/main/resources/application.yaml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-451

#447 PUB-2359 Removed calls to channel-management
  Jenkinsfile_CNP
  README.md
  charts/pip-publication-services/Chart.yaml
  charts/pip-publication-services/values.yaml
  publication-services-arch.png
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionNotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementServiceTest.java
  src/test/resources/application-test.yaml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-447

#453 PUB-2535 - Updated to handle both body and header
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, test/add-or-update, rel:pip-publication-services-pr-453

#454 PUB-2535 - Updated APIM
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, test/add-or-update, rel:pip-publication-services-pr-454

#452 PUB-2511: Updating dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/no-changes, prod/no-changes, rel:pip-publication-services-pr-452
