Repository hmcts/pip-publication-services, pull requests merged in 2024-06, with the labels that each got.

#434 PUB-2471 - Batch subscription sending
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/Application.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/emaildata/subscription/FlatFileSubscriptionEmailData.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/emaildata/subscription/RawDataSubscriptionEmailData.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/BulkSubscriptionEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/SingleSubscriptionEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/SubscriptionEmail.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionNotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/FlatFileSubscriptionEmailGenerator.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/RawDataSubscriptionEmailGenerator.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/configuration/AsyncConfig.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/FlatFileSubscriptionEmailGeneratorTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/RawDataSubscriptionEmailGeneratorTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-434

#435 PUB-2363 - Update Data Models version number
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-435

#436 PUB-2461: Upgrading to Java 21
  Dockerfile
  README.md
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-436

#433 PUB-2454 - Update pip-data-models with new list type IAC Daily
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-433

#441 PUB-2490 - Updated jenkins nightly time
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-441
