Repository hmcts/pip-publication-services, pull requests merged in 2024-10, with the labels that each got.

#468 PUB-2566 Move functional tests to integration test folder
  Jenkinsfile_CNP
  README.md
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/NotificationEmailTests.java
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/utils/AuthException.java
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/utils/FunctionalTestBase.java
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/utils/OAuthClient.java
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/utils/RedisConfigurationTestBase.java
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyRateLimitTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/utils/RedisConfigurationTestBase.java
  src/integrationTest/resources/application-integration-rate-limit.yaml
  src/integrationTest/resources/application-integration.yaml
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-468

#469 PUB-2612 - Allow empty email summary
  README.md
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionNotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionNotificationServiceTest.java
  src/test/resources/application-test.yaml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-469

#471 PUB-2535 - Test Env
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, test/add-or-update, rel:pip-publication-services-pr-471

#472 PUB-2633 - Testing JWT part 2 change in Test
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, test/add-or-update, rel:pip-publication-services-pr-472

#473 PUB-2633 - Change back perftest
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-473

#456 PUB-2535 - Updated validate JWT
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-publication-services-pr-456

#457 PUB-2535 - Updated validate JWT part 2
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-publication-services-pr-457

#470 PUB-2618 - Updated dependencies
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/no-changes, prod/no-changes, rel:pip-publication-services-pr-470

#474 PUB-2498 Update subscription email format
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/RawDataSubscriptionEmailGenerator.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/RawDataSubscriptionEmailGeneratorTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-474
