Repository hmcts/pip-publication-services, pull requests merged in 2024-01, with the labels that each got.

#398 PUB-2245 - Updated README
  README.md
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-398

#400 PUB-2182 add terraform_format.yml
  .github/workflows/terraform_format.yml
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/providers.tf
  infrastructure/stg.tfvars
  infrastructure/test.tfvars
  infrastructure/tf-apim-api.tf
  infrastructure/tf-apim-operations.tf
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-400

#406 Merge code freeze branch to Master
  .github/workflows/terraform_format.yml
  README.md
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/providers.tf
  infrastructure/stg.tfvars
  infrastructure/test.tfvars
  infrastructure/tf-apim-api.tf
  infrastructure/tf-apim-operations.tf
Labels: ns:pip, prd:pip, no-changes, rel:pip-publication-services-pr-406

#401 PUB-2279 - Fixed code smells
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/B2cNotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationService.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-401

#408 PUB-2208 Update pip-data-models version for OPA results
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-408

#407 PUB-2133 - Updated version of spring boot
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/SpringSecurityConfig.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/configuration/SpringSecurityConfigTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-407

#399 PUB-2269 Update OTP APIM
  infrastructure/data.tf
  infrastructure/resources/api-policy/api-policy.xml
  infrastructure/resources/operation-policies/sendOtpEmail.xml
  infrastructure/resources/operation-policies/welcome.xml
  infrastructure/tf-apim-api.tf
  infrastructure/tf-apim-operations.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-publication-services-pr-399

#410 PUB-1619 - Enable fortify on nightly
  Jenkinsfile_nightly
  README.md
  build.gradle
  config/fortify-client.properties
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-410

#411 Updated KV name
  Jenkinsfile_nightly
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-411

#412 PUB-1619 - Added fortify library classifier
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-412
