Repository hmcts/pip-publication-services, pull requests merged in 2024-09, with the labels that each got.

#459 PUB-2535 - Updated validate JWT
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, test/add-or-update, rel:pip-publication-services-pr-459

#460 PUB-2535 - Part 2
  infrastructure/resources/operation-policies/sendOtpEmail.xml
Labels: ns:pip, prd:pip, stg/add-or-update, test/add-or-update, rel:pip-publication-services-pr-460

#458 PUB-1567 Add email for crime inactive user
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/PersonalisationLinks.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/useraccount/InactiveUserNotificationEmailGenerator.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/notify/TemplatesTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/useraccount/InactiveUserNotificationEmailGeneratorTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-458
