Repository hmcts/pip-publication-services, pull requests merged in 2025-07, with the labels that each got.

#532 PUB-2903 Add PCOL Daily Cause List
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-532

#536 PUB-2896 - Added new list type
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-536

#537 PUB-2740 - Updated to new dependencycheck
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-537
