Repository hmcts/pip-publication-services, pull requests merged in 2025-03, with the labels that each got.

#509 PUB-2739 Add Asylum Support Tribunal Daily Hearing List
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-509

#510 PUB-2721 Add Mental Health Hearing List
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-510

#475 PUB-2638 - Update data models version number
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-475

#511 PUB-2807 - Updated limit for MI report
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/client/WebClientCreationTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-511

#512 PUB-2827 - Updated helm chart
  charts/pip-publication-services/Chart.yaml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-512
