Repository hmcts/pip-publication-services, pull requests merged in 2025-05, with the labels that each got.

#501 PUB-2728 Update calls to account-management after subscription merge
  Jenkinsfile_parameterized
  README.md
  build.gradle
  charts/pip-publication-services/Chart.yaml
  charts/pip-publication-services/values.dev.template.yaml
  charts/pip-publication-services/values.stg.template.yaml
  charts/pip-publication-services/values.yaml
  publication-services-arch.png
  service-diagram.png
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/BatchNotificationEmailTests.java
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/NotificationEmailTests.java
  src/functionalTest/java/uk/gov/hmcts/pip/publication/services/SubscriptionNotificationEmailTests.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifySubscriptionTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/utils/IntegrationTestBase.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/emaildata/subscription/LocationSubscriptionDeletionEmailData.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/subscription/LocationSubscriptionDeletionEmailGeneratorTest.java
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-501

#521 PUB-2817 - Dependency updates
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/no-changes, prod/no-changes, rel:pip-publication-services-pr-521

#517 PUB-2846 Add RCJ list types
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-517

#523 Rolls Building Non-Strategic Publishing - Part 2
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-523
