Repository hmcts/pip-publication-services, pull requests merged in 2025-02, with the labels that each got.

#505 PUB-2758 Monthly dependency update
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/no-changes, prod/no-changes, rel:pip-publication-services-pr-505

#507 PUB-2755 Add SSCS Daily Hearing Lists
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-507

#506 PUB-2756 - Changes to First Tier Tribunal Hearing lists
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-506
