Repository hmcts/pip-publication-services, pull requests merged in 2025-06, with the labels that each got.

#527 PUB-2899 - Updated to AzureDevOps
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-527

#530 PUB-2883 - Update UT IAC regional lists
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-publication-services-pr-530

#531 PUB-2878 - Monthly Dependencies
  .github/workflows/terraform_format.yml
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
  infrastructure/providers.tf
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationService.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationServiceTest.java
Labels: ns:pip, prd:pip, stg/no-changes, prod/no-changes, rel:pip-publication-services-pr-531
